[workspace]

members = [
    "apps", "tnet", "collections", "model", "solver", "sat", "env_param", "utils"
]

[profile.dev]
opt-level = 2               # Use slightly better optimizations.


[profile.release]
debug = true                # Debug symbols for benchmarking
opt-level = 3
lto = "thin"
codegen-units = 8
panic = "abort"