[workspace]

members = [
    "solver",
    "env_param",
    "planning/planning",
    "planning/planners",
    "planning/grpc/api",
    "planning/grpc/server",
    "examples/sat",
    "examples/scheduling",
    "examples/smt",
    "examples/gg",
    "examples/knapsack",
    "validator",
]
resolver = "2"

[workspace.dependencies]
anyhow = { version = "1.0" }
clap = { version = "4.4", features = ["derive"] }
num-rational = { version = "0.4.1" }
regex = { version = "1" }
tracing = { version = "0.1", features = ["release_max_level_debug"] }
tracing-subscriber = "0.3"
itertools = { version = "0.12.1" }
rand = { version = "0.8.5", features = ["small_rng"] }

[profile.dev]
opt-level = 0

[profile.release]
codegen-units = 8
debug = false # No debug symbols to keep executables small
lto = "thin"
opt-level = 3
panic = "abort"

# A profile meant for usage in CI, provide reasonable build/execution times. Also enables debug assertions and symbols.
[profile.ci]
inherits = "dev"
opt-level = 3
