[package]
name = "aries_knapsack"
version = "0.1.0"
authors = ["Arthur Bit-Monnot <abitmonnot@laas.fr>"]
edition = "2018"

[dependencies]
aries_core = { path = "../../core" }
aries_model = { path = "../../model" }
aries_solver = { path = "../../solver" }
aries_cp = { path = "../../reasoners/cp" }


[[bin]]
name = "aries-knapsack"
path = "main.rs"