[package]
name = "aries_sat"
version = "0.1.0"
authors = ["Arthur Bit-Monnot <abitmonnot@laas.fr>"]
edition = "2018"

[dependencies]
structopt = "0.3"
anyhow = "1.0"
aries_model = { path = "../../model" }
aries_solver = { path = "../../solver" }
varisat-dimacs = "0.2.2"
varisat-formula = "0.2.2"
zip = "0.5"


[[bin]]
name = "aries-sat"
path = "main.rs"